//tabla tareas
CREATE TABLE task (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR (200) NOT NULL,
    description VARCHAR (400) NOT NULL,
    donde BOOLEAN NOT NULL DEFAULT 0,
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);